name: Build Eleventy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: docker

    strategy:
      matrix:
        node-version: ["22.x"]

    steps:
      - name: Checkout repository
        uses: https://github.com/actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: https://github.com/actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npx @11ty/eleventy

      - name: Deploy to VPS
        uses: https://github.com/burnett01/rsync-deployments@v8
        with:
          switches: -avzr --delete
          path: _site/
          remote_path: ${{ secrets.VPS_BLOG_REMOTE_PATH }}
          remote_host: ${{ secrets.VPS_SSH_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.VPS_SSH_USER }}
          remote_key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
